#!/usr/bin/env python
import curses
import sys
import json

def app(stdscr, data):
  while 1:
    c = stdscr.getch()
    if c == ord('q'): break
    stdscr.addstr("%s\n" % data[chr(c)])
    stdscr.refresh()

def main():
  with open(sys.argv[1]) as f:
    data = json.load(f)
  curses.wrapper(app, data)

if __name__ == '__main__':
  main()
