#!/usr/bin/env python
# Copyright (c) 2012, Etienne Millon
#
# "THE BEER-WARE LICENSE" (Revision 42):
# <me@emillon.org> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return Poul-Henning Kamp

import atexit
import curses
import subprocess
import sys
import json

def play(filename):
  p = subprocess.Popen(['/usr/bin/mplayer', '-really-quiet', filename])
  def kill_it():
    p.kill()
  atexit.register(kill_it)

def app(stdscr, data):
  while 1:
    c = stdscr.getch()
    if c == ord('q'): break
    k = chr(c)
    f = data[chr(c)]
    stdscr.addstr("%s\n" % f)
    stdscr.refresh()
    play(f)

def main():
  with open(sys.argv[1]) as f:
    data = json.load(f)
  curses.wrapper(app, data)

if __name__ == '__main__':
  main()
